# Theme Settings
theme: null   # REQUIRED because you're using a remote theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0" # REQUIRED to specify the theme and version

# Site Settings
locale                   : "en-US"
title                    : "GD 2027"
name                     : "Graph Drawing 2027, Budapest"
description              : ""
url                      : "https://graphdrawing.github.io/gd2027/"
teaser                   : "/assets/images/teaser/budapestView.png"
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : true # true, false (default)

# Site Author
author:
  name             : "GD 2027"
  avatar           : "/assets/images/logo/gdlogo-2027-transparent.png"
  bio              : "The 35th International Symposium on Graph Drawing and Network Visualization will be held at Rényi Institute in Budapest, Hungary from September 15-17, 2027. A PhD school will take place on September 13-14, 2027."
  location         : "HUN-REN Alfréd Rényi Institute of Mathematics, Budapest, Hungary"
#  email            : ""
  links:
    - label: "Contact Organizers"
      icon: "fas fa-fw fa-envelope-square"
      # url: "mailto:rnishat@brocku.ca,d.mondal@usask.ca"
    - label: "Contact PC chairs"
      icon: "fas fa-fw fa-envelope-square"
      # url: "mailto:gd2026@easychair.org"
    - label: "graphdrawing.org"
      icon: "fas fa-fw fa-link"
      url: "http://graphdrawing.org"
    - label: "Previous Years"
      icon: "fas fa-history"
      url: "http://graphdrawing.org/symposium.html"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url: "https://github.com/graphdrawing"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"


# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/graphdrawing"
    # - label: "Facebook"
      # icon: "fab fa-fw fa-facebook-square"
      # url: "https://www.facebook.com/graphdrawing.org/"
    #- label: "Twitter"
      # icon: "fab fa-fw fa-twitter-square"
      # url:
    #- label: "GitLab"
      # icon: "fab fa-fw fa-gitlab"
      # url:
    #- label: "Bitbucket"
      # icon: "fab fa-fw fa-bitbucket"
      # url:
    #- label: "Instagram"
      # icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"


plugins:
  - jekyll-remote-theme
  - jekyll-include-cache # REQUIRED to use include_cached
  - jekyll-feed
  - jekyll-seo-tag

