# Theme Settings
theme: null   # REQUIRED because you're using a remote theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0" # REQUIRED to specify the theme and version

# Site Settings
title             : "Graph Drawing 2027, Budapest"
name              : "Graph Drawing 2027, Budapest"
description       : "This is the website of the conference Graph Drawing 2027, to be held in Budapest"
url               : "https://graphdrawing.github.io/gd2027"
teaser            : "/assets/images/teaser/teaser.png"

# Site Author
author:
  name            : "Graph Drawing 2027"
#  avatar          : "/assets/images/photos/2023.jpg"
#  bio             : "I am a geometer."
#  location        : "Hungary"
#  email           :
#  links:
#    - label: "Email"
#      icon: "fas fa-fw fa-envelope-square"
#      url: "mailto:marton.naszodi@renyi.hu"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache # REQUIRED to use include_cached
  - jekyll-feed
  - jekyll-seo-tag
